In [1]:
# simply execute the script
!python search_counts.py

unique searches: 5
auto-suggest searches: 2
percentage of searches using auto-suggest: 40.0%

In [2]:
import search_counts

In [3]:
df = search_counts.build_dataset()

In [4]:
df

,UserId,Timestamp,SearchTerm,search_ts,tdelta,prev_search,lv_dist,new_search_user,new_search_time,new_search_word,new_composite
0,35d54e11793a211b,2020-01-01 00:00:26.211000,LOW,2020-01-01 00:00:26.211,NaT,NaN,3,True,False,False,True
1,35d54e11793a211b,2020-01-01 00:00:31.099000,brk lft fib,2020-01-01 00:00:31.099,0 days 00:00:04.888000,LOW,11,False,False,True,True
2,79698bf7950dd5f8,2020-01-01 00:00:24.982000,ac,2020-01-01 00:00:24.982,NaT,brk lft fib,11,True,False,True,True
3,79698bf7950dd5f8,2020-01-01 00:00:24.999000,acu,2020-01-01 00:00:24.999,0 days 00:00:00.017000,ac,1,False,False,False,False
4,79698bf7950dd5f8,2020-01-01 00:00:25.012000,acut,2020-01-01 00:00:25.012,0 days 00:00:00.013000,acu,1,False,False,False,False
5,79698bf7950dd5f8,2020-01-01 00:00:25.193000,acute n,2020-01-01 00:00:25.193,0 days 00:00:00.181000,acut,3,False,False,False,False
6,79698bf7950dd5f8,2020-01-01 00:00:25.207000,acute nas,2020-01-01 00:00:25.207,0 days 00:00:00.014000,acute n,2,False,False,False,False
7,79698bf7950dd5f8,2020-01-01 00:00:25.250000,acute naso,2020-01-01 00:00:25.250,0 days 00:00:00.043000,acute nas,1,False,False,False,False
8,79698bf7950dd5f8,2020-01-01 00:00:25.298000,acute nasop,2020-01-01 00:00:25.298,0 days 00:00:00.048000,acute naso,1,False,False,False,False
9,79698bf7950dd5f8,2020-01-01 00:00:25.333000,acute nasoph,2020-01-01 00:00:25.333,0 days 00:00:00.035000,acute nasop,1,False,False,False,False
10,79698bf7950dd5f8,2020-01-01 00:00:25.582000,acute nasopha,2020-01-01 00:00:25.582,0 days 00:00:00.249000,acute nasoph,1,False,False,False,False
11,79698bf7950dd5f8,2020-01-01 00:00:25.714000,acute nasophar,2020-01-01 00:00:25.714,0 days 00:00:00.132000,acute nasopha,1,False,False,False,False
12,79698bf7950dd5f8,2020-01-01 00:00:35.012000,acute nasophar,2020-01-01 00:00:35.012,0 days 00:00:09.298000,acute nasophar,0,False,False,False,False
13,96b3cea2160f0b28,2020-01-01 00:00:30.512000,obes,2020-01-01 00:00:30.512,NaT,acute nasophar,12,True,False,True,True
14,96b3cea2160f0b28,2020-01-01 00:00:31.077000,obese,2020-01-01 00:00:31.077,0 days 00:00:00.565000,obes,1,False,False,False,False
15,96b3cea2160f0b28,2020-01-01 00:00:31.234000,obes,2020-01-01 00:00:31.234,0 days 00:00:00.157000,obese,1,False,False,False,False
16,96b3cea2160f0b28,2020-01-01 00:00:31.543000,obesi,2020-01-01 00:00:31.543,0 days 00:00:00.309000,obes,1,False,False,False,False
17,a85fab26f7c400f9,2020-01-01 00:00:26.228000,Fi,2020-01-01 00:00:26.228,NaT,obesi,4,True,False,True,True

In [5]:
search_count = search_counts.unique_searches(df)
print(f"unique searches: {search_count}")

unique searches: 5

In [6]:
autosugg_count = search_counts.autosugg_searches(df)
print(f"auto-suggest searches: {autosugg_count}")

auto-suggest searches: 2

In [7]:
pct_auto = round(autosugg_count / search_count * 100, 2)
print(f"percentage of searches using auto-suggest: {pct_auto}%")

percentage of searches using auto-suggest: 40.0%